# 배열의 분리

In [1]:
import numpy as np

In [3]:
array = np.arange(10).reshape(2, 5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
detach1 = np.split(array, 2, axis=0)
detach1

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [6]:
detach2 = np.split(array, [2, 3], axis=1)
detach2

[array([[0, 1],
        [5, 6]]),
 array([[2],
        [7]]),
 array([[3, 4],
        [8, 9]])]