# Array Broadcasting

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4]).reshape(2, 2)
array1

array([[1, 2],
       [3, 4]])

In [3]:
array2 = np.array([1, 2])
array2

array([1, 2])

In [6]:
add = array1 + array2
# 같은 행과 열끼리 연산이 이루어짐
add

array([[2, 4],
       [4, 6]])

### ndarray
 - 행렬에 블록 단위로 접근하는 방식과 동일
 - 슬라이싱을 통해 원하는 영역의 범위를 설정하고 새로운 ndarray 클래스에 할당
 > 슬라이싱(배열[start:end:step, start:end:step])
 - 관심영역, 관심채널

In [15]:
# 관심영역
array = np.zeros((1280, 1920, 3), np.uint8)

In [11]:
x, y, w, h = 100, 100, 300, 300
roi = array[x:x+w, y:y+h]

In [13]:
array.shape

(1280, 1920, 3)

In [14]:
roi.shape

(300, 300, 3)

In [17]:
# 관심채널
coi = array[:, :, 0]

In [18]:
coi.shape

(1280, 1920)