In [1]:
import cv2
import numpy as np

In [4]:
image = cv2.imread('mountain.jpg')
image

array([[[ 63,  62,  58],
        [ 63,  62,  58],
        [ 63,  62,  58],
        ...,
        [ 78,  71,  68],
        [ 79,  72,  69],
        [ 79,  72,  69]],

       [[ 63,  62,  58],
        [ 63,  62,  58],
        [ 63,  62,  58],
        ...,
        [ 78,  71,  68],
        [ 78,  71,  68],
        [ 78,  71,  68]],

       [[ 63,  62,  58],
        [ 63,  62,  58],
        [ 63,  62,  58],
        ...,
        [ 79,  72,  69],
        [ 78,  71,  68],
        [ 78,  71,  68]],

       ...,

       [[ 25,  29,  34],
        [ 22,  26,  31],
        [ 24,  28,  33],
        ...,
        [ 66,  79,  93],
        [ 72,  85, 101],
        [ 65,  77,  95]],

       [[ 26,  30,  35],
        [ 24,  28,  33],
        [ 26,  30,  35],
        ...,
        [ 48,  61,  75],
        [ 54,  64,  81],
        [ 50,  62,  80]],

       [[ 26,  29,  37],
        [ 25,  28,  36],
        [ 28,  32,  37],
        ...,
        [ 43,  54,  68],
        [ 39,  47,  64],
        [ 32,  42,  60]]

In [5]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
gray

array([[61, 61, 61, ..., 71, 72, 72],
       [61, 61, 61, ..., 71, 71, 71],
       [61, 61, 61, ..., 72, 71, 71],
       ...,
       [30, 27, 29, ..., 82, 88, 81],
       [31, 29, 31, ..., 64, 68, 66],
       [31, 30, 33, ..., 57, 51, 46]], dtype=uint8)

In [9]:
result = np.zeros((image.shape[0], 256), dtype=np.uint8)
result

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [10]:
print(image.shape, gray.shape, result.shape)

(853, 1280, 3) (853, 1280) (853, 256)


In [11]:
hist = cv2.calcHist([image], [0], None, [256], [0, 256])
# (원본 이미지, 0번 채널, mask=None, 히스토그램 사이즈=256(0~255), range)
cv2.normalize(hist, hist, 0, 255, cv2.NORM_MINMAX)

array([[2.55000000e+02],
       [1.76901207e+01],
       [2.44424973e+01],
       [2.94370270e+01],
       [3.21993637e+01],
       [3.84774055e+01],
       [4.22721291e+01],
       [4.99173889e+01],
       [5.20100632e+01],
       [5.52746506e+01],
       [5.95995178e+01],
       [6.49288788e+01],
       [6.61286774e+01],
       [6.91421356e+01],
       [7.48063278e+01],
       [7.71780319e+01],
       [8.62184067e+01],
       [8.84505997e+01],
       [9.62353668e+01],
       [1.01229897e+02],
       [1.05722183e+02],
       [1.14037086e+02],
       [1.17552803e+02],
       [1.25532875e+02],
       [1.31224976e+02],
       [1.34433746e+02],
       [1.40042114e+02],
       [1.46096954e+02],
       [1.50672943e+02],
       [1.56895172e+02],
       [1.65489105e+02],
       [1.68139832e+02],
       [1.71739258e+02],
       [1.73831940e+02],
       [1.75868805e+02],
       [1.77068604e+02],
       [1.80919128e+02],
       [1.81309784e+02],
       [1.80751709e+02],
       [1.88369080e+02],


In [12]:
print(hist.shape)

(256, 1)


In [15]:
for x, y in enumerate(hist):
    cv2.line(result, (int(x), image.shape[0]), (int(x), image.shape[0] - int(y)), 255)

In [18]:
dst = np.hstack([image[:,:,0], result])

In [22]:
cv2.imshow('dst', dst) # 창 이름 설정

In [25]:
cv2.waitKey(0)

48

In [26]:
cv2.destroyAllWindows()