In [2]:
import numpy as np
import cv2

In [4]:
src = cv2.imread('book.jpg')
data = src.reshape(-1, 3).astype(np.float32)
data.shape

(2449920, 3)

In [5]:
K = 3

In [6]:
criteria = (cv2.TERM_CRITERIA_MAX_ITER + cv2.TERM_CRITERIA_EPS, 10, 0.001)

In [7]:
retval, bestLabels, centers = cv2.kmeans(
    data, K, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)

In [8]:
centers = centers.astype(np.uint8)
dst = centers[bestLabels].reshape(src.shape)
print(centers, centers.shape)

[[150 173 198]
 [230 232 234]
 [ 26  56 144]] (3, 3)


In [8]:
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()